name                         = "ecs-todo-app"
vpc_cidr_block               = "10.0.0.0/16"
public_subnet_cidr_block     = "10.0.1.0/24"
availability_zone            = "eu-central-1a"
instance_type                = "t3.micro"
key_name                     = "ecs-todo-app-key"
key_filename                 = "ecs-todo-app-key.pem"