variable name {}
variable vpc_cidr_block {}
variable public_subnet_cidr_block {}
variable instance_type {}
variable key_name {}
variable key_filename {}
variable container_port {}
variable aws_region {}
variable private_subnet_1_cidr_block {}
variable private_subnet_2_cidr_block {}
variable public_subnet_cidr_block_2 {}
variable desired_count {}