variable name {}
variable vpc_cidr_block {}
variable public_subnet_cidr_block {}
variable availability_zone {}
variable instance_type {}
variable key_name {}
variable key_filename {}
variable container_port {}
variable aws_region {}